IMAGE_NAME = "hashicorp/bionic64"
IMAGE_VERSION = "1.0.282"

MASTER_MEMORY = 1024
MASTER_CPUS = 2

N_NODE = 2
NODE_MEMORY = 2048
NODE_CPUS = 2

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.box_version = IMAGE_VERSION
        master.vm.provider "virtualbox" do |v|
            v.memory = MASTER_MEMORY
            v.cpus = MASTER_CPUS
        end
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..N_NODE).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.box_version = IMAGE_VERSION
            node.vm.provider "virtualbox" do |v|
                v.memory = NODE_MEMORY
                v.cpus = NODE_CPUS
            end
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end
end
