-
  name: Setup environment
  hosts: worker
  tasks:
    - name: install pip3
      apt:
        name: python3-pip
        state: present
      become: true

    - name: Copy requirements.txt
      copy:
        src: packages/requirements.txt
        dest: /home/vagrant/requirements.txt

    - name: Install requirements
      pip:
        requirements: /home/vagrant/requirements.txt